### ISSUE TITLE
bit file for lua 5.3

### ISSUE THREAD

**Issue by Edgexue** [cyrilis/lua-pinyin#1]
Hi. thanks a lot for the contribution.
I just want to add that the bit file is not built-in. In fact, most online lib only provides bit file that allows lua5.1/5.2, the searching process is also very painful!. 
As my personal suggestion, I recommend fellow users to personally write a bit file, which only needs to include 3 functions, namely (bitand--band, bitor--bor, bit_left_shift--blshift)

**Comment by cyrilis** [comment]
Hi @Edgexue , 

Sorry for this late reply. This repo is actual only tested in [Luvit](http://luvit.io/), which is an "Asynchronous I/O for Lua" implementation, however however it's not very active any more. Thanks for your trying and suggestion.

**Comment by cyrilis** [comment]
I'm closing for now, if you have further questions, please reopen it or create another issue.
